accounts/urls.py
from django.urls import path


from . import views


app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('user/', views.user, name='user'),
]

auth_user/urls.py
import django.contrib.auth.views
from django.urls import path,include
from . import views
app_name='auth_user'

urlpatterns=[
    path('top/',views.top_page, name="top"), # リダイレクト
    path('login/', # ログイン
         django.contrib.auth.views.LoginView.as_view(),
         {
             'template_name': 'auth_user/login.html',
         },
         name='login'),
    path('logout/', # ログアウト
         django.contrib.auth.views.LogoutView.as_view(),
         {
             'template_name': 'auth_user/logout.html',
         },
         name='logout'),
]

onomato/urls.py
from django.urls import path

from . import views


app_name = 'onomato'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('tos/', views.tos, name='tos'),
    path('contact/', views.contact, name='contact'),
    path('odai/', views.odai_index, name='odai_index'),
    path('odai/<int:odai_id>/', views.odai_detail, name='odai_detail'),
]

onomatopoiia/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('onomato.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  # 標準ユーザー機能のために追加
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

onomato/models.py
from django.db import models


class Odai(models.Model):
    odai_text = models.CharField(max_length=4)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return f'<{self.odai_text}>'


class Answer(models.Model):
    odai = models.ForeignKey(Odai, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=50, null=False)
    pub_date = models.DateTimeField('date published')
    # user = models.ForeignKey(User, on_delete=models.CASCADE)  # TODO: 回答のユーザー情報をログイン機能と共に追加

    def __str__(self):
        return f'<{self.odai.odai_text}:{self.answer_text}>'

# TODO: 試しコード？ 不要であれば消す。
# class User(models.Model):
#     user_name = models.CharField(max_length=10)

onomato/forms.py
from django import forms
from .models import Answer


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('answer_text',)


# ↓ 岩崎くんのコード。一旦コメントアウト。
# class AnswerForm(forms.ModelForm):
#     class Meta:
#         model = Answer
#         fields = ('answer_text',)
#         # TODO: 回答のユーザー情報を追加

# TODO: 試しコード。いらなくなったら消す。
# class AnswerForm(forms.Form):
# #    odai = forms.CharField()
#    answer_text = forms.CharField()

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'


@login_required
def user(request):
    user = request.user
    return render(request, 'accounts/user.html', {'user': user})

auth_user/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from social_django.models import UserSocialAuth


@login_required
def top_page(request):
    user = UserSocialAuth.objects.get(user_id=request.user.id)

    return render(request,'top.html',{'user': user})

onomato/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.utils import timezone


from .models import Odai, Answer
from .forms import AnswerForm


def index(request):
    latest_answer = Answer.objects.order_by('-pub_date')[:5]
    context = {
        'latest_answer': latest_answer,
    }
    return render(request, 'index.html', context)


def odai_index(request):
    latest_odai = Odai.objects.order_by('-pub_date')
    context = {'latest_odai': latest_odai}
    return render(request, 'odai.html', context)


def about(request):
    return render(request, 'about.html')


def tos(request):
    return render(request, 'tos.html')


def contact(request):
    return render(request, 'contact.html')


def odai_detail(request, odai_id):
    odai = Odai.objects.get(id=odai_id)
    is_login = request.user.is_authenticated

    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)  # フォームの内容を保存(DBには反映しない)
            # フォームで入力された値以外を埋める
            answer.odai = odai
            answer.pub_date = timezone.now()
            answer.save()  # 再び保存(DBに反映)
            # TODO: url の指定がハードコーディングなため、修正の必要がある
            # この書き方だとエラー
            # return redirect('odai_detail', {'odai_id': odai_id})
            return redirect(f'/odai/{odai_id}')
        else:
            form = AnswerForm()
            context = {'odai': odai, 'form': form, 'is_login': is_login}
            return render(request, 'odai_detail.html', context)

    else:
        context = {'odai': odai, 'is_login': is_login}
        return render(request, 'odai_detail.html', context)

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% block link %}
<link rel="stylesheet" href="{% static '/css/signup.css' %}" />
{% endblock %} 
{% block content %}
<div class="main__signup">
<form action="" class="main__signup__form" method="POST">
  <h1 class="main__signup__form__title">新規登録</h1>
  {% csrf_token %}
    <div class="main__signup__form__error-message">
      {{form.non_field_erros }}
    </div>
    <div class="main__signup__form__item">
      <label for="{{ form.username.id_for_label }}" class="main__signup__form__item__label">
        ユーザー名
      </label>
        <div class="main__signup__form__item__field">
        	{{ form.username }}
        </div>
        <div class="main__signup__form__item__error">
            {{ form.username.errors }}
        </div>
    </div>
    <div class="main__signup__form__item">
      <label for="{{ form.password1.id_for_label }}" class="main__signup__form__item__label">
        パスワード
      </label>
        <div class="main__signup__form__item__field">
            {{ form.password1 }}
        </div>
        <div class="main__signup__form__item__error">
            {{ form.password1.errors }}
        </div>
    </div>
    <div class="main__signup__form__item">
      <label for="{{ form.password2.id_for_label }}" class="main__signup__form__item__label">
        パスワード（確認用）
      </label>
        <div class="main__signup__form__item__field">
            {{ form.password2 }}
        </div>
        <div class="main__signup__form__item__error">
            {{ form.password2.errors }}
        </div>
    </div>
          <input type="submit" value="登録" class="main__signup__form__item__submit"></input>
  </form>
</div>
{% endblock %}

accounts/templates/accounts/user.html
{% extends 'base.html' %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static '/css/user.css' %}" />
{% endblock %} {% block content %}
<div class="main__user">
  <div class="main__user__username">
    <p>こんにちは、{{ user }}さん！</p>
  </div>
  <div class="main__user__profile">
    <p>ユーザー毎の回答に関する機能は現在未実装です。</p>
  </div>
</div>
{% endblock %}

auth_user/templates/top.html
<html>
<head>
    <title>TOP</title>
</head>
<body>
    <div>
        <a href="/twitterManager/logout"><button type="button" >ログアウト</button></a>
    </div>
<div>
    <div>
      <p><b>ScreenName</b>:{{ user.access_token.screen_name }}</p>
        <p><b>UserId</b>:{{ user.access_token.user_id }}</p>
        <p><b>OAuthTokenSecret</b>:{{ user.access_token.oauth_token_secret }}</p>
        <p><b>OAuthToken</b>:{{ user.access_token.oauth_token }}</p>
        <p><b>AuthTime</b>:{{ user.extra_data.auth_time }}</p>


    </div>
</div>
</body>
</html>

onomato/templates/onomato/about.html
{% extends 'onomato/base.html' %}
{% load static %}
{% block link %}
<link rel="stylesheet" href="{% static 'onomato/css/about.css' %}" />
{% endblock %}
{% block content %}
<div class="main__abouts">
  <ul class="main__abouts__list">
    <li class="main__abouts__concept main__abouts__list__item" id="main__abouts__concept">
      <h2 class="main__abouts__title">
        onomatopoiia へようこそ！
      </h2>
      <div class="main__abouts__text">
        <p>
          onomatopoiia（オノマトポイーア）は未知のオノマトペにしっくりくる、<br />
          「ぽい」説明や概念をみんなで考えるゆるふわ大喜利系サイトです。
        </p>
      </div>
    </li>
    <li class="main__abouts__onomatopee main__abouts__list__item" id="main__abouts__onomatopee">
      <h2 class="main__abouts__title">
        オノマトペ とは？
      </h2>
      <div class="main__abouts__text">
        <p>
          オノマトペ（onomatopoeia, onomatopee）は<br />
          「ワンワン」「パチパチ」「ワクワク」などの、
          擬声語や擬音語、擬態語を<br />
          指す言葉です。 （元来の意味は擬声語のみらしいです。）
        </p>
      </div>
    </li>
    <li class="main__abouts__asobikata main__abouts__list__item" id="main__abouts__asobikata">
      <h2 class="main__abouts__title">遊び方</h2>
      <div class="main__abouts__text">
        <p>
          お題となるオノマトペに<strong>20文字以内</strong>で概念を書いて遊びましょう。<br />
          お題例 : パチパチ
          <ul>
            <li>回答例 1 : 線香花火の様子</li>
            <li>回答例 2 : 電気の流れる音</li>
            <li>回答例 3 : 賭け事に勤しむ様子</li>
          </ul>
          「どういう風に答えるのか分からない」という人は、<br />
          他の人の回答を見て感覚を掴むのもアリだと思います。<br />
          思いつきで書いたものが案外しっくり来たりするかも...！？

        <p>※ お願い</p>
          下ネタや誹謗中傷（他人を傷つける）を含む内容は書かないようにしてください。<br>
          削除させていただく場合があります。
        </p>
        <a href="/onomato/odai/" class="main__abouts__asobikata__odai-link">
          お題を見てみる
        </a>
      </div>
    </li>

    <li class="main__abouts__contact" id="main__abouts__contact"></li>
  </ul>
</div>
{% endblock %}

onomato/templates/onomato/contact.html
{% extends 'onomato/base.html' %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'onomato/css/contact.css' %}" />
{% endblock %} {% block content %}
<div class="main__contact">
  <h2 class="main__contact__title">お問い合わせ</h2>
  <div class="main__contact__content">
    <p>お問い合わせフォームは現在作成途中です。</p>
    <ul class="main__contact__content__list">
      <li>お名前</li>
      <li>件名</li>
      <li>内容</li>
    </ul>
    <p>を記載して、以下の画像のe-mailアドレス宛にメールをご送信ください。</p>
    <img
      class="main__contact__address-image"
      src="{% static 'onomato/img/address-mini.jpg' %}"
      alt="メールアドレス画像"
      width="200"
    />
  </div>
</div>
{% endblock %}

onomato/templates/onomato/index.html
{% extends 'onomato/base.html' %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'onomato/css/index.css' %}" />
{% endblock %} {% block content %}
<div class="main__top">
  <div class="main__top__first-view">
    <p>
      未だ知らぬオノマトペを開拓しよう！
    </p>
  </div>
  <a href="/onomato/about/" class="main__top__top-nav">遊び方 </a>
  <a href="/onomato/odai/" class="main__top__top-nav">全てのお題を見る </a>
  <a href="/onomato/odai/" class="main__top__top-nav">ランダムにお題を選ぶ </a>
  <div class="main__top__latest-answers">
    <h2 class="main__top__latest-answers__title">最新の回答</h2>
    {% if latest_answer %} {% for answer in latest_answer %}
    <div class="main__top__latest-answers__answer">
      <div class="main__top__latest-answers__answer__odai-answer">
        <p class="main__top__latest-answers__answer__odai-answer__odai-text">
          {{ answer.odai.odai_text }}
        </p>
        <div
          class="main__top__latest-answers__answer__odai-answer__answer-text"
        >
          {{ answer.answer_text }}
        </div>
      </div>
      <a
        href="/onomato/odai/{{ answer.odai.id }}"
        class="main__top__latest-answers__answer__detail-link"
      >
        <div>
          <div class="main__top__latest-answers__answer__detail-link__text">
            回答を見る
          </div>
          <div class="main__top__latest-answers__answer__detail-link__text">
            回答する
          </div>
        </div>
      </a>
    </div>
    {% endfor %} {% else %} {% endif %}
  </div>
</div>
{% endblock %}

onomato/templates/onomato/odai.html
{% extends 'onomato/base.html' %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'onomato/css/odai.css' %}" />
{% endblock %} {% block content %}
<div class="main__odais">
  {% if latest_odai %}
  <h2 class="main__odais__title">お題一覧（新着順）</h2>
  {% for odai in latest_odai %}
  <div class="main__odais__odai">
    <div class="main__odais__odai__text">
      {{ odai.odai_text }}
    </div>
    <a
      href="/onomato/odai/{{ odai.id }}"
      class="main__odais__odai__detail-link"
    >
      <div>
        <div class="main__odais__odai__detail-link__text">
          回答を見る
        </div>
        <div class="main__odais__odai__detail-link__text">
          回答する
        </div>
      </div>
    </a>
  </div>
  {% endfor %} {% else %}
  <p>お題はまだ無いよ。</p>
  {% endif %}
</div>
{% endblock %}

onomato/templates/onomato/odai_detail.html
{% extends 'onomato/base.html' %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'onomato/css/odai_detail.css' %}" />
{% endblock %} {% block content %}
<div class="main__kaitou">
  <div class="main__kaitou__odai">
    <h2 class="main__kaitou__odai-text">{{ odai.odai_text }}</h2>
  </div>

  <form method="POST" class="main__kaitou__form">
    {% csrf_token %}
    <label for="answer_text">これはなに？</label>
    <input
      type="text"
      name="answer_text"
      placeholder="20文字まで"
      maxlength="20"
      required
      autofocus
    />
    <input type="submit" value="送信" class="main__kaitou__form__submit" />
  </form>
  <div class="main__kaitou__kaitous">
    {% if odai.answer_set.all %} {% for q in odai.answer_set.all %}
    <div class="main__kaitou__kaitous__kaitou">
      <p>{{q.answer_text}}</p>
    </div>
    {% endfor %} {% else %}
    <div class="main__kaitou__no-kaitou-message">
      <p>まだ概念がありません。</p>
      <p>あなたが第一人者になろう！</p>
    </div>
    {% endif %}
  </div>
  <div class="main__kaitou__links">
    <a href="/onomato/odai/" class="main__kaitou__links__odai-link"
      >お題一覧へ<br />戻る</a
    >
    <a href="/onomato/odai/" class="main__kaitou__links__odai-link"
      >別のお題に<br />行く</a
    >
  </div>
</div>
{% endblock %}

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block link %}
<link rel="stylesheet" href="{% static '/css/about.css' %}" />
{% endblock %}
{% block content %}
<div class="main__abouts">
  <ul class="main__abouts__list">
    <li class="main__abouts__concept main__abouts__list__item" id="main__abouts__concept">
      <h2 class="main__abouts__title">
        onomatopoiia へようこそ！
      </h2>
      <div class="main__abouts__text">
        <p>
          onomatopoiia（オノマトポイーア）は カナ 2 文字 × 2 のオノマトペにしっくりくる
          <strong>「ぽい」</strong>説明や概念をみんなで考える、ゆるふわ大喜利系サイトです。
          未知のオノマトペはもちろん、既存のオノマトペに新たな意味を添えるのも一興。
          今日からあなたも「<strong>言の葉を紡ぎし者  <ruby>擬声戦士<rp><rt>オノマトパー</rt></rp></ruby>（☆8 儀式モンスター）</strong>」だ！
        </p>
      </div>
    </li>
    <li class="main__abouts__onomatopee main__abouts__list__item" id="main__abouts__onomatopee">
      <h2 class="main__abouts__title">
        オノマトペ とは？
      </h2>
      <div class="main__abouts__text">
        <p>
          オノマトペ（onomatopoeia, onomatopee）は<br />
          「ワンワン」「パチパチ」「ワクワク」などの、
          擬声語や擬音語、擬態語を
          指す言葉です。 （元来の意味は擬声語のみらしいです。）
          日本語におけるオノマトペの歴史は、日本最古の歴史書である古事記にも記されているそうです。
          私達が残したオノマトペもいずれ歴史となり未来人にとって高尚なものになるのでしょう。
        </p>
      </div>
    </li>
    <li class="main__abouts__asobikata main__abouts__list__item" id="main__abouts__asobikata">
      <h2 class="main__abouts__title">遊び方</h2>
      <div class="main__abouts__text">
        <p>
          お題となるオノマトペに<strong>20文字以内</strong>で回答して遊びましょう。<br />
          <p>お題例 : パチパチ</p>
          <ul>
            <li>回答例 1 : 線香花火の様子</li>
            <li>回答例 2 : 電気の流れる音</li>
            <li>回答例 3 : 賭け事に勤しむ様子</li>
          </ul>
          「どういう風に答えるのか分からない」「思いつかない」という人は、<br />
          他の人の回答を見て感覚を掴むのもアリだと思います。<br />
          思いつきで書いたものが案外しっくり来たりするかも...！？

        <p>※ お願い</p>
          下ネタや誹謗中傷（他人を傷つける）を含む内容は書かないようにしてください。<br>
          回答を削除させていただく場合があります。
        </p>
        <a href="{% url 'onomato:odai_index' %}" class="main__abouts__asobikata__odai-link">
          お題を見てみる
        </a>
      </div>
    </li>

    <li class="main__abouts__contact" id="main__abouts__contact"></li>
  </ul>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type="image/png" href="{% static '/img/favicon.ico' %}" />
    <link rel="stylesheet" href="{% static '/css/reset.css' %}" />
    <link rel="stylesheet" href="{% static '/css/base.css' %}" />
    {% block link %}{% endblock %}
    <title>onomatopoiia</title>
  </head>
  <body>
    <header class="header">
      <h1>
        <a href="{% url 'onomato:index' %}" class="header__title">
          onomatopoiia
        </a>
      </h1>
      <nav class="header__nav">
        <ul class="header__nav__list">
          <a href="{% url 'onomato:odai_index' %}">
            <li class="header__nav__list__item">お題</li>
          </a>
          {% if request.user.is_authenticated %}
          <li class="header__nav__list__item user" id="user-tab">
            <p class="user__text">
              {{ request.user.username | truncatechars:7 }}
            </p>
            <ul class="user__user-menu hidden" id="user-menu">
              <a href="{% url 'accounts:user' %}">
                <li class="user-menu__item">マイページ</li>
              </a>
              <a href="{% url 'logout' %}">
                <li class="user-menu__item">ログアウト</li>
              </a>
            </ul>
          </li>
          {% else %}
          <a href="{% url 'login' %}" class="header__nav__list__item login">
            <li>ログイン</li>
          </a>
          <a
            href="{% url 'accounts:signup' %}"
            class="header__nav__list__item signup"
          >
            <li>新規登録</li>
          </a>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main class="main">
      {% block content %} {% endblock %}
    </main>
    <footer class="footer">
      <div class="footer__abouts">
        <ul>
          <a href="{% url 'onomato:about' %}"><li>このサイトについて</li></a>
          <a href="{% url 'onomato:tos' %}"><li>利用規約等</li></a>
          <a href="{% url 'onomato:contact' %}"><li>お問い合わせ</li></a>
        </ul>
      </div>
      <div class="footer__copyright">
        <p>
          (c) 2020 onomatopoiia
        </p>
      </div>
    </footer>
  </body>
  <script>
    // Chrome の読み込み時の transition が効くのを防ぐための空コード
  </script>
  <script src="{% static '/js/base.js' %}"></script>
  {% block script %} {% endblock %}
</html>

templates/contact.html
{% extends 'base.html' %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static '/css/contact.css' %}" />
{% endblock %} {% block content %}
<div class="main__contact">
  <h2 class="main__contact__title">お問い合わせ</h2>
  <div class="main__contact__content">
    <p>お問い合わせフォームは現在作成途中です。</p>
    <ul class="main__contact__content__list">
      <li>お名前</li>
      <li>件名</li>
      <li>内容</li>
    </ul>
    <p>を記載して、以下の画像のe-mailアドレス宛にメールをご送信ください。</p>
    <img
      class="main__contact__address-image"
      src="{% static '/img/address-mini.jpg' %}"
      alt="メールアドレス画像"
      width="200"
    />
  </div>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static '/css/index.css' %}" />
{% endblock %} {% block content %}
<div class="main__top">
  <div class="main__top__first-view">
    <p class="main__top__first-view__catch-copy">
      今日から君も オノマトパー。
    </p>
    <p class="main__top__first-view__catch-copy english">
      You are "ONOMATOPER" from today!
    </p>
    <p class="main__top__first-view__text text--1">フワフワ</p>
    <p class="main__top__first-view__text text--2">サクサク</p>
    <p class="main__top__first-view__text text--3">スボスボ</p>
    <p class="main__top__first-view__text text--4">フムフム</p>
    <p class="main__top__first-view__text text--5">ヨヌヨヌ</p>
    <p class="main__top__first-view__text text--6">ヘケヘケ</p>
    <p class="main__top__first-view__text text--7">グゲグゲ</p>
    <p class="main__top__first-view__text text--8">ポベポベ</p>
    <p class="main__top__first-view__text text--9">オノオノ</p>
    <p class="main__top__first-view__text text--10">マグマグ</p>
    <p class="main__top__first-view__text text--11">クナクナ</p>
    <p class="main__top__first-view__text text--12">グビグビ</p>
    <p class="main__top__first-view__text text--13">ヌフヌフ</p>
    <p class="main__top__first-view__text text--14">イコイコ</p>
  </div>
  <div class="main__top__navs">
    <a href="{% url 'onomato:about' %}" class="main__top__navs__item">遊び方</a>
    <a href="{% url 'onomato:odai_index' %}" class="main__top__navs__item">
      お題一覧
    </a>
    <a href="#" class="main__top__navs__item disabled">
      ランダムお題
    </a>
  </div>
  <div class="main__top__latest-answers">
    <h2 class="main__top__latest-answers__title">最新の回答</h2>
    {% if latest_answer %} {% for answer in latest_answer %}
    <div class="main__top__latest-answers__answer">
      <div class="main__top__latest-answers__answer__odai-answer">
        <p class="main__top__latest-answers__answer__odai-answer__odai-text">
          {{ answer.odai.odai_text }}
        </p>
        <div
          class="main__top__latest-answers__answer__odai-answer__answer-text"
        >
          {{ answer.answer_text }}
        </div>
      </div>
      {% comment %} HACK: href がハードコーディングなので url を使って書き換える
      {% endcomment %}
      <a
        href="odai/{{ answer.odai.id }}"
        class="main__top__latest-answers__answer__detail-link"
      >
        <div>
          <div class="main__top__latest-answers__answer__detail-link__text">
            回答を見る
          </div>
          <div class="main__top__latest-answers__answer__detail-link__text">
            回答する
          </div>
        </div>
      </a>
    </div>
    {% endfor %} {% else %} {% endif %}
  </div>
</div>
{% endblock %}

templates/odai.html
{% extends 'base.html' %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static '/css/odai.css' %}" />
{% endblock %} {% block content %}
<div class="main__odais">
  {% if latest_odai %}
  <h2 class="main__odais__title">お題一覧（新着順）</h2>
  {% for odai in latest_odai %}
  <div class="main__odais__odai">
    <div class="main__odais__odai__text">
      {{ odai.odai_text }}
    </div>
    {% comment %} HACK: href を url を使って書く {% endcomment %}
    <a href="/odai/{{ odai.id }}" class="main__odais__odai__detail-link">
      <div>
        <div class="main__odais__odai__detail-link__text">
          回答を見る
        </div>
        <div class="main__odais__odai__detail-link__text">
          回答する
        </div>
      </div>
    </a>
  </div>
  {% endfor %} {% else %}
  <p>お題はまだありません。</p>
  {% endif %}
</div>
{% endblock %}

templates/odai_detail.html
{% extends 'base.html' %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static '/css/odai_detail.css' %}" />
{% endblock %} {% block content %}
<div class="main__kaitou">
  <div class="main__kaitou__odai">
    <h2 class="main__kaitou__odai-text">{{ odai.odai_text }}</h2>
  </div>
  {% if is_login %}
  <form action="" method="POST" class="main__kaitou__form">
    {% csrf_token %}
    <label for="answer_text">これはなに？</label>
    <input
      type="text"
      id="answer_text"
      name="answer_text"
      class="main__kaitou__form__text"
      placeholder="20文字まで"
      maxlength="20"
      required
      autofocus
    />
    <input type="submit" value="送信" class="main__kaitou__form__submit" />
    {% else %}
    <div class="main__kaitou__not-login">
      <p class="main__kaitou__not-login__text">ログインすると回答できます。</p>
      <a href="{% url 'login' %}" class="main__kaitou__not-login__login-link">
        ログイン
      </a>
      <a
        href="{% url 'accounts:signup' %}"
        class="main__kaitou__not-login__signup-link"
      >
        新規登録
      </a>
    </div>
    {% endif %}
  </form>
  <div class="main__kaitou__kaitous">
    {% if odai.answer_set.all %} {% for q in odai.answer_set.all %}
    <div class="main__kaitou__kaitous__kaitou">
      <p>{{q.answer_text}}</p>
    </div>
    {% endfor %} {% else %}
    <div class="main__kaitou__no-kaitou-message">
      <p>まだ概念がありません。</p>
      <p>あなたが第一人者になろう！</p>
    </div>
    {% endif %}
  </div>
  <div class="main__kaitou__links">
    <a
      href="{% url 'onomato:odai_index' %}"
      class="main__kaitou__links__odai-link"
      >お題一覧</a
    >
    <a href="#" class="main__kaitou__links__odai-link disabled">ランダムお題</a>
  </div>
</div>
{% endblock %}